import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'package:sqlite3/sqlite3.dart';
import 'package:sqlite3_flutter_libs/sqlite3_flutter_libs.dart';

// This file will be generated by drift automatically
part 'app_database.g.dart';

// 1. Define the Projects Table
class Projects extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  TextColumn get clientName => text().nullable()();
  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();

  @override
  Set<Column> get primaryKey => {id};
}

// 2. Define the Appliances Table
class AppliancesTable extends Table {
  TextColumn get id => text()();
  TextColumn get projectId => text().nullable()(); // Links appliance to a specific project
  TextColumn get name => text()();
  TextColumn get category => text()();
  IntColumn get quantity => integer()();
  RealColumn get runningWatts => real()();
  RealColumn get surgeMultiplier => real()();
  RealColumn get dailyHours => real()();
  RealColumn get dutyCycle => real().withDefault(const Constant(1.0))();

  @override
  Set<Column> get primaryKey => {id};
}

// 3. Configure the Database Connection
@DriftDatabase(tables: [Projects, AppliancesTable])
class AppDatabase extends _$AppDatabase {
  // Allow passing a custom executor (like an in-memory one for tests)
  AppDatabase({QueryExecutor? e}) : super(e ?? _openConnection());

  @override
  int get schemaVersion => 1;
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'solarpro_db.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}